name: Build

on: [push, pull_request]

jobs:    
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

# SET ENVIRONMENT VARIABLES WE WILL USE IN LATER STEPS
# For more information on setting environment variables in GitHub Actions, 
# see https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable 

    # - name: "Store current time in variable"
    #   run: echo "CURRENT_TIME=$(date +'%Y-%m-%d_%s')" >> $GITHUB_ENV

    # - name: "Is this a push to the Main branch?"
    #   if: ${{ github.ref == 'refs/heads/main' }}
    #   run: echo "REALM_APP_ID=application-cicd-hrhpz" >> $GITHUB_ENV

# INSTALL THE REALM-CLI AND AUTHENTICATE

# For more information on the MongoDB Realm CLI, 
# see https://docs.mongodb.com/realm/deploy/realm-cli-reference/
# Adding --realm-url and --atlas-url to login command to workaround authentication error  
    - name: "Install the Realm CLI & authenticate"
      run: |
           npm install -g mongodb-realm-cli@beta
           realm-cli login --api-key="vjsoynii" --private-api-key="a65be2cf-5229-4810-8a2a-33991968d701" --realm-url https://realm.mongodb.com --atlas-url https://cloud.mongodb.com

# PUSH THE REALM APP

    - name: "Push updated copy of the Realm app for existing apps (Main, Staging, or Feature branches)"
      run: | 
           realm-cli push --remote=application-cicd-hrhpz -y