name: MongoBD CI/CD Deploying

on: [push]

jobs:    
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.5.0

    - name: "Store current time in variable"
      run: echo "CURRENT_TIME=$(date +'%Y-%m-%d_%s')" >> $GITHUB_ENV

    - name: "Is this a push to the Main branch?"
      if: ${{ github.ref == 'refs/heads/main' }}
      run: echo "REALM_APP_ID=application-cicd-hrhpz" >> $GITHUB_ENV

    - name: "Install the Realm CLI & authenticate"
      run: |
           npm install -g mongodb-realm-cli
           realm-cli login --api-key="vjsoynii" --private-api-key="a65be2cf-5229-4810-8a2a-33991968d701" --realm-url https://realm.mongodb.com --atlas-url https://cloud.mongodb.com

    - name: "Push updated copy of the Realm app for existing apps (Main, Staging, or Feature branches)"
      if: ${{ env.REALM_APP_ID }}
      run: | 
           realm-cli push --remote="${{ env.REALM_APP_ID }}" -y